config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  mount Sidekiq::Web => '/sidekiq'

  root to: 'pages#home'

  resources :campaigns, except: [:new] do
    post 'raffle', on: :member
    # post 'raffle', on: :collection
  end

  resources :members, only: [:create, :destroy, :update]

  get 'members/:token/opened', to: 'members#opened'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :create, :show, :update, :destroy]
      resources :campaigns, only: [:index, :create, :show, :update, :destroy]
      resources :members, only: [:index, :create, :show, :update, :destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :user
  has_many :members, dependent: :destroy
  before_validation :set_member, on: :create
  before_validation :set_status, on: :create
  enum status: [:pending, :finished]
  validates :title, :user, :status, presence: true

  def count_opened
    self.members.where(open: true).count
  end

  private

  def set_status
    self.status = :pending
  end

  def set_member
    self.members << Member.create(name: self.user.name, email: self.user.email)
  end
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :campaign
  after_save :set_campaign_pending
  validates :name, :email, :campaign, presence: true

  after_destroy :set_campaign_pending

  def set_pixel
    self.open = false
    self.token = loop do
      random_token = SecureRandom.urlsafe_base64(nil, false)
      break random_token unless Member.exists?(token: random_token)
    end
    self.save!
  end

  protected

  def set_campaign_pending
    self.campaign.update(status: :pending)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  has_many :campaigns, dependent: :destroy
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  protect_from_forgery with: :null_session

  before_action :destroy_session

  def destroy_session
    request.session_options[:skip] = true
  end
end

app/controllers/api/v1/campaigns_controller.rb
class Api::V1::CampaignsController < Api::V1::BaseController
  def index
    campaigns = Campaign.all
    render json: campaigns, include: :members
  end

  def show
    campaign = Campaign.find(params[:id])
    render json: campaign, include: :members
  end
end

app/controllers/api/v1/members_controller.rb
class Api::V1::MembersController < Api::V1::BaseController
  def index
    members = Member.all
    render json: members
  end

  def show
    member = Member.find(params[:id])
    render json: member
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController
  def index
    users = User.all
    render json: users, include: { campaigns: { include: :members } }
  end

  def show
    user = User.find(params[:id])
    render json: user, include: { campaigns: { include: :members } }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from ActiveRecord::RecordNotFound, :with => :render_404

  def render_404
    # TODO Create page 404
    redirect_to '/404'
    # redirect_to main_app.root_url
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_campaign, only: [:show, :destroy, :update, :raffle]
  before_action :is_owner?, only: [:show, :destroy, :update, :raffle]

  def show
  end

  def index
    @campaigns = current_user.campaigns
  end

  def create
    @campaign = Campaign.new(
      user: current_user, title: 'New Campaign'
    )

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to "/campaigns/#{@campaign.id}" }
      else
        format.html { redirect_to main_app.root_url, notice: @campaign.errors }
      end
    end
  end

  def update
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.json { render json: true }
      else
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @campaign.destroy

    respond_to do |format|
      format.json { render json: true }
    end
  end

  def raffle
    respond_to do |format|
      if @campaign.status != "pending"
        @campaign.update(status: :finished)

        format.json { render json: 'Already been raffle', status: :unprocessable_entity }
      elsif @campaign.members.count < 3
        format.json { render json: 'Campaign needs at least 3 members', status: :unprocessable_entity }
      else
        # CampaignRaffleJob.perform_later @campaign
        @campaign.update(status: :finished)

        format.json { render json: true }
      end
    end
  end

  private

  def set_campaign
    @campaign = Campaign.find(params[:id])
  end

  def campaign_params
    params.require(:campaign).permit(:title, :description, :event_date, :event_hour, :locale).merge(user: current_user)
  end

  def is_owner?
    unless current_user == @campaign.user
      respond_to do |format|
        format.json { render json: false, status: :forbidden }
        format.html { redirect_to main_app.root_url }
      end
    end
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_user!, except: [:opened]

  before_action :set_member, only: [:show, :destroy, :update]
  before_action :is_owner?, only: [:destroy, :update]
  before_action :set_member_by_token, only: [:opened]

  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.json { render json: @member }
      else
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @member.destroy

    respond_to do |format|
      format.json { render json: true }
    end
  end

  def update
    respond_to do |format|
      if @member.update(member_params)
        format.json { render json: true }
      else
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  def opened
    @member.update(open: true)
    gif = Base64.decode64("R0lGODlhAQABAPAAAAAAAAAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==")
    render text: gif, type: 'image/gif'
  end

  private

  def set_member
    @member = Member.find(params[:id])
  end

  def set_member_by_token
    @member = Member.find_by!(token: params[:token])
  end

  def member_params
    params.require(:member).permit(:name, :email, :campaign_id)
  end

  def is_owner?
    unless current_user == @member.campaign.user
      respond_to do |format|
        format.json { render json: false, status: :forbidden }
      end
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController
  def show
    user = User.find(params[:id])
    render(json: user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
  def open_number(campaign)
    "#{campaign.count_opened}/#{campaign.members.count}"
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/campaigns/index.html.erb
<div class="row campaigns">
  <div class="col s8 offset-s2">
    <% if @campaigns.any? %>
      <p class="title">Campaigns</p>
    <% else %>
      <h4 class="title-new"><b> Add new campaigns</b></h4>
      <p class="subtitle-new"><i>Click the "+" button</i></p>
    <% end %>
  </div>
  <div class="row cards">
    <div class="col s8 offset-s2">
      <% @campaigns.each do |c| %>
        <div class="card horizontal">
          <div class="card-content col s12">
            <div class="col s12 l8 m12">
              <div class="row">
                <div class="col s8 m9 l9">
                  <p class="title"><%= truncate(c.title, length: 30, omission: '...') %></p>
                </div>
                <div class="col s4 m2 l2">
                  <p class="data"><%= (c.event_date)? c.event_date.strftime("%d/%m/%y") : '' %></p>
                </div>
              </div>
              <div class="row">
                <div class="col s12 m12 l12">
                  <p class="subtitle"><%= truncate(c.description, length: 70, omission: '...') %></p>
                </div>
              </div>
              <div class="row status">
                <div class="col s6 m6 l4 visibility">
                  <i class="material-icons visibility-icon">visibility</i>
                  <span class="visibility-text">Viewed <%= open_number(c) %></span>
                </div>
                <div class="col s2 m2 offset-s4 l2 offset-l6">
                  <span class="new badge <%= (c.status == "pending")? 'orange' : '' %>"> <%= (c.status == "pending")? 'Pending' : 'Raffle' %> </span>
                </div>
              </div>
            </div>
            <div class="col l4 s12 m12 center enter">
              <div class="row">
                <div class="col s12">
                  <a class="waves-effect waves-light btn grey" href=<%= "/campaigns/#{c.id}" %>>Look</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="fixed-action-btn campaigns-btn">
    <%= form_tag("/campaigns", method: "post") do %>
      <button class="btn-floating btn-large red pulse" type="submit">
        <i class="large material-icons">add</i>
      </button>
    <% end %>
  </div>
</div>

app/views/campaigns/show.html.erb
<div class="row campaigns">
  <div class="col s8 offset-s2">
    <p class="title">Info Campaign</p>
  </div>

  <div class="campaign">
    <div class="row cards">
      <div class="col s8 offset-s2">
        <div class="card horizontal">
          <div class="card-content col s12">
            <%= form_for @campaign, url: {action: "update"}, html: {class: "col s12 update_campaign"} do |f| %>
              <div class="row">
                <div class="row">
                  <div class="col s12 l4 input-field">
                    <%= f.text_field :title, 'data-length': "20" %>
                    <label for="title" class="<%= (@campaign.title)? 'active' : '' %>">Title</label>
                  </div>
                  <div class="col s12 l3 input-field">
                    <%= f.date_field :event_date, class: 'datepicker' %>
                    <label for="title" class="<%= (@campaign.event_date)? 'active' : '' %>">Date</label>
                  </div>
                  <div class="col s12 l2 input-field">
                    <%= f.text_field :event_hour, class: 'timepicker' %>
                    <label for="title" class="<%= (@campaign.event_hour)? 'active' : '' %>">Hour</label>
                  </div>
                  <div class="col s12 l3 input-field">
                    <%= f.text_field :locale, 'data-length': "20" %>
                    <label for="title" class="<%= (@campaign.locale)? 'active' : '' %>">Locale</label>
                  </div>
                </div>
                <div class="row">
                  <div class="col s12 input-field">
                    <%= f.text_field :description, 'data-length': "150" %>
                    <label for="title" class="<%= (@campaign.description)? 'active' : '' %>">Description</label>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="col s8 offset-s2">
      <p class="title">Members</p>
    </div>

    <div class="row cards members">
      <div class="col s8 offset-s2">
        <div class="card horizontal">
          <div class="card-content col s12">

          <div class="member_list">
            <% @campaign.members.each do |m| %>
              <div class="member" id="member_<%= m.id %>">
                <div class="row">
                  <div class="col s12 m5 input-field">
                    <input id="name" type="text" class="validate" value="<%= m.name %>">
                    <label for="name" class="active">Name</label>
                  </div>
                  <div class="col s12 m5 input-field">
                    <input id="email" type="email" class="validate" value="<%= m.email %>">
                    <label for="email" class="active" data-error="Wrong format">Email</label>
                  </div>
                  <div class="col s3 offset-s3 m1 input-field">
                    <i class="material-icons icon <%= (m.open)? 'opened' : '' %>">visibility</i>
                  </div>
                  <div class="col s3 m1 input-field">
                    <a href="#" class="remove_member" id="<%= m.id %>">
                      <i class="material-icons icon">delete</i>
                    </a>
                  </div>
                </div>
              </div>
            <% end %>
          </div>

          <%= form_for(Member.new) do |f| %>
            <div class="member">
              <div class="row">
                <%= f.hidden_field :campaign_id, value: @campaign.id %>
                <div class="col s12 m5 input-field">
                  <%= f.text_field :name, class: "validate"%>
                  <label for="name" class="active">Name</label>
                </div>
                <div class="col s12 m5 input-field">
                  <%= f.email_field :email, class: "validate" %>
                  <label for="member[email]" class="active" data-error="Wrong format">Email</label>
                </div>
                <div class="col s12 m2 input-field">
                  <%= form_tag(members_path(), method: 'post', class: 'new_member') do %>
                    <button type='submit' class="waves-effect waves-light btn red">New</button>
                  <% end %>

                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="row btn-actions">
    <div class="col s12 center">
      <div class="col s6 m3 offset-m3 l2 offset-l4">
        <%= form_for @campaign, method: 'delete', html: {class: 'remove_campaign'} do |f| %>
          <button type='submit' class="waves-effect waves-light btn grey">Delete</button>
        <% end %>
      </div>
      <div class="col s6 m3 l3">
        <%= form_tag(raffle_campaign_path(@campaign), method: 'post', class: 'raffle_campaign') do %>
          <button type='submit' class="waves-effect waves-light btn red">Raffle</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecretSantaGift</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag %>
  </head>

  <body>

    <header>
      <%= render "shared/navbar" %>
    </header>

    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>

    <footer>
      <%= render "shared/footer" %>
    </footer>

  </body>
</html>

app/views/pages/home.html.erb
<div class="row home">
  <div class="center">
    <h4 class="title">Surprise in the Secret Santa Gift</h4>
    <h5 class="subtitle">Create your raffle with just the name and email of your friends</h5>
    <h5 class="subtitle2">Fast and Guaranteed <i class="material-icons home-icon">favorite</i></h5>

    <%= form_tag("/campaigns", method: "post") do %>
      <%= submit_tag("Create Now", class: "waves-effect waves-light btn home-button") %>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="page-footer">
  <div class="container">
    <div class="copyright">
      <b>Created with
        <i class="material-icons copyright-icon">favorite</i>
        <a class="copyright-link" href="#"> by Team Secret Santa</a>
      </b>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-fixed">
  <nav class="top-nav">
    <div class="nav-wrapper col s12">
      <a href="/" class="brand-logo">
        <%= image_tag("logo.png", class: "logo-img") %>
        <span class="logo-title">
          Secret Santa Gift
        </span>
      </a>

      <a href="#" data-activates="side-bar" class="button-collapse"><i class="material-icons">menu</i></a>

      <ul class="right hide-on-med-and-down">
        <% if current_user %>
          <li><a href="/campaigns">Campaigns</a></li>
          <li><a href="/users/edit">Profile</a></li>
          <li>  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
        <% else %>
          <li><a href="/users/sign_in">Sign in</a></li>
          <li><a href="/users/sign_up">Sign up</a></li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

<ul class="side-nav" id="side-bar">
  <% if current_user %>
    <li><a href="/campaigns">Campaigns</a></li>
    <li><a href="/users/edit">Profile</a></li>
    <li><div class="divider"></div></li>
    <li>  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
  <% else %>
    <li><a href="/users/sign_in">Sign in</a></li>
    <li><div class="divider"></div></li>
    <li><a href="/users/sign_up">Sign up</a></li>
    <li><div class="divider"></div></li>
  <% end %>
</ul>